### PR TITLE
fix: calculated network hash rate

### LINKED ISSUE #3: Info route returns best_block_hash instead of network_hash_rate
Screenshot from 2024-03-25 12-09-27

As you can see in the image above, the `network_hash_rate` is actually a hash of a block.

### PR DESCRIPTION
**Pull request by yemmyharry**
closes #3

### CODE REVIEW

**Review by theedtron — COMMENTED** [review]
Will it be more accurate to calculate difficulty/blocktime of 600s to get hashrate?

**Comment by yemmyharry** [comment]
> Will it be more accurate to calculate difficulty/blocktime of 600s to get hashrate?

the formula for calculating network hash rate is hash_rate = (blocks_found/expected_blocks*difficulty * 2**32 / 600)

**Comment by theedtron** [comment]
Formula is Hash rate = (Difficulty*2^32)/600

**Comment by yemmyharry** [comment]
> Formula is Hash rate = (Difficulty*2^32)/600

check out https://bitcoin.stackexchange.com/questions/11139/how-is-the-network-hash-rate-calculated

**Comment by theedtron** [comment]
> > Formula is Hash rate = (Difficulty*2^32)/600
> 
> check out https://bitcoin.stackexchange.com/questions/11139/how-is-the-network-hash-rate-calculated

Also got it from stackexchange
https://bitcoin.stackexchange.com/questions/90661/what-is-the-formula-for-inferring-hash-rate-from-difficulty-and-block-frequency#103709

We need to figure out whether they both compute the same result

**Comment by yemmyharry** [comment]
> > > Formula is Hash rate = (Difficulty*2^32)/600
> > 
> > 
> > check out https://bitcoin.stackexchange.com/questions/11139/how-is-the-network-hash-rate-calculated
> 
> Also got it from stackexchange https://bitcoin.stackexchange.com/questions/90661/what-is-the-formula-for-inferring-hash-rate-from-difficulty-and-block-frequency#103709
> 
> We need to figure out whether they both compute the same result

they actually do. i tested it out

**Comment by theedtron** [comment]
Great in that case we are good to go

**Review by theedtron — APPROVED** [review]

**Pull request merged**
